### ISSUE TITLE
Memory access fault by GPU node-1 on address 0x1e4000. Reason: Page not present or supervisor privilege.

### ISSUE THREAD

**Issue by mmmmming18** [ROCmSoftwarePlatform/hiptensorflow#60]
I was training ResNet training on CIFAR-10 data and I got this error.

INFO:tensorflow:loss = 1.35363, step = 501, precision = 0.609375
INFO:tensorflow:global_step/sec: 1.63348
INFO:tensorflow:loss = 1.16574, step = 601, precision = 0.671875
INFO:tensorflow:global_step/sec: 1.63298
INFO:tensorflow:loss = 1.14607, step = 701, precision = 0.679688
INFO:tensorflow:global_step/sec: 1.63824
INFO:tensorflow:loss = 1.11029, step = 801, precision = 0.710938
INFO:tensorflow:global_step/sec: 1.63955
INFO:tensorflow:loss = 1.00229, step = 901, precision = 0.703125
Memory access fault by GPU node-1 on address 0x1e4000. Reason: Page not present or supervisor privilege.
Aborted (core dumped)

Thanks

**Comment by parallelo** [comment]
Hi @mmmmming18, 

Can you give more details on your system setup?  

Thanks, 

Jeff

**Comment by parallelo** [comment]
Hello again @mmmmming18, 

On a Vega machine with ROCm 1.7 installed, we were able to train ResNet on CIFAR-10 data.  

We've got a couple known workarounds that may be useful for you.  These will be included in an upcoming release.  Anyway, we want you to be able to make progress in the meantime, so here they are:  
```
sudo sh -c 'echo "options amdkfd noretry=0"        >> /etc/modprobe.d/amdkfd.conf'
sudo sh -c 'echo "options amdgpu vm_update_mode=0" >> /etc/modprobe.d/amdgpu.conf'
sudo update-initramfs -u
# then reboot
```

Please give this a try and let us know how it goes.  

Here's an example of the output:  
```
# python ./resnet_main.py --train_data_path=cifar10/data_batch* --log_root=/tmp/resnet_model --train_dir=/tmp/resnet_model/train --dataset='cifar10' --num_gpus=1
...
I tensorflow/core/common_runtime/gpu/gpu_device.cc:886] Found device 0 with properties: 
name: Device 6860
major: 3 minor: 0 memoryClockRate (GHz) 1.5
pciBusID 0000:07:00.0
Total memory: 15.98GiB
Free memory: 15.73GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:907] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:917] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:966] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Device 6860, pci bus id: 0000:07:00.0)
I tensorflow/core/kernels/conv_ops.cc:604] running auto-tune for Convolve
I tensorflow/core/kernels/conv_ops.cc:604] running auto-tune for Convolve
I tensorflow/core/kernels/conv_ops.cc:604] running auto-tune for Convolve
I tensorflow/core/kernels/conv_ops.cc:604] running auto-tune for Convolve
I tensorflow/core/kernels/conv_ops.cc:604] running auto-tune for Convolve
I tensorflow/core/kernels/conv_ops.cc:604] running auto-tune for Convolve
I tensorflow/core/kernels/conv_grad_input_ops.cc:764] running auto-tune for Backward-Data
I tensorflow/core/kernels/conv_grad_filter_ops.cc:615] running auto-tune for Backward-Filter
I tensorflow/core/kernels/conv_grad_input_ops.cc:764] running auto-tune for Backward-Data
I tensorflow/core/kernels/conv_grad_filter_ops.cc:615] running auto-tune for Backward-Filter
I tensorflow/core/kernels/conv_grad_input_ops.cc:764] running auto-tune for Backward-Data
I tensorflow/core/kernels/conv_grad_filter_ops.cc:615] running auto-tune for Backward-Filter
I tensorflow/core/kernels/conv_grad_input_ops.cc:764] running auto-tune for Backward-Data
I tensorflow/core/kernels/conv_grad_filter_ops.cc:615] running auto-tune for Backward-Filter
I tensorflow/core/kernels/conv_grad_filter_ops.cc:615] running auto-tune for Backward-Filter
I tensorflow/core/kernels/conv_grad_input_ops.cc:764] running auto-tune for Backward-Data
I tensorflow/core/kernels/conv_grad_filter_ops.cc:615] running auto-tune for Backward-Filter
INFO:tensorflow:Saving checkpoints for 2 into /tmp/resnet_model/model.ckpt.
INFO:tensorflow:loss = 2.53896, step = 2, precision = 0.101562
INFO:tensorflow:global_step/sec: 1.42451
INFO:tensorflow:loss = 1.78081, step = 102, precision = 0.398438
INFO:tensorflow:global_step/sec: 1.4665
INFO:tensorflow:loss = 1.54725, step = 202, precision = 0.5
INFO:tensorflow:global_step/sec: 1.46563
INFO:tensorflow:loss = 1.41548, step = 302, precision = 0.617188
INFO:tensorflow:global_step/sec: 1.46696
INFO:tensorflow:loss = 1.2178, step = 402, precision = 0.65625
INFO:tensorflow:global_step/sec: 1.46671
INFO:tensorflow:loss = 1.36942, step = 502, precision = 0.5625
INFO:tensorflow:global_step/sec: 1.46659
INFO:tensorflow:loss = 1.1598, step = 602, precision = 0.664062
INFO:tensorflow:global_step/sec: 1.46141
INFO:tensorflow:loss = 1.14987, step = 702, precision = 0.671875
INFO:tensorflow:global_step/sec: 1.46801
INFO:tensorflow:loss = 1.10011, step = 802, precision = 0.703125
INFO:tensorflow:Saving checkpoints for 879 into /tmp/resnet_model/model.ckpt.
INFO:tensorflow:global_step/sec: 1.44525
INFO:tensorflow:loss = 1.22131, step = 902, precision = 0.6875
INFO:tensorflow:global_step/sec: 1.46582
INFO:tensorflow:loss = 1.0695, step = 1002, precision = 0.671875
INFO:tensorflow:global_step/sec: 1.46839
INFO:tensorflow:loss = 0.968387, step = 1102, precision = 0.757812
INFO:tensorflow:global_step/sec: 1.46993
INFO:tensorflow:loss = 1.04134, step = 1202, precision = 0.703125
INFO:tensorflow:global_step/sec: 1.46703
INFO:tensorflow:loss = 0.755976, step = 1302, precision = 0.820312
INFO:tensorflow:global_step/sec: 1.46624
INFO:tensorflow:loss = 0.799054, step = 1402, precision = 0.796875
INFO:tensorflow:global_step/sec: 1.4685
INFO:tensorflow:loss = 0.895221, step = 1502, precision = 0.742188
INFO:tensorflow:global_step/sec: 1.46718
INFO:tensorflow:loss = 0.737785, step = 1602, precision = 0.796875
INFO:tensorflow:global_step/sec: 1.47167
INFO:tensorflow:loss = 0.747813, step = 1702, precision = 0.820312
INFO:tensorflow:Saving checkpoints for 1759 into /tmp/resnet_model/model.ckpt.
```

**Comment by Yurail** [comment]
my system has 1950x + vega fe *3

2018-01-26 12:37 GMT+09:00 Jeff Poznanovic <notifications@github.com>:

**Comment by parallelo** [comment]
@mmmmming18 - Any luck trying the suggested workaround?

**Comment by mmmmming18** [comment]
@parallelo Sorry parallelo,

we tried to install "tensorflow_gpu-1.head-cp27-cp27mu-linux_x86_64.whl" version but it didn't work out. Then, no matter how we re-install the original version, TF is always giving the same error.

import tensorflow as tf
Traceback (most recent call last):
File "", line 1, in 
File "/usr/local/lib/python2.7/dist-packages/tensorflow/init.py", line 24, in 
from tensorflow.python import *
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/init.py", line 72, in 
raise ImportError(msg)
ImportError: Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/init.py", line 61, in 
from tensorflow.python import pywrap_tensorflow
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in 
_pywrap_tensorflow = swig_import_helper()
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
_mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: libhip_hcc.so: cannot open shared object file: No such file or directory

In order to try your workarounds, we might try to clean the os and re-install everything.

**Comment by parallelo** [comment]
Does this help?  
```
export LD_LIBRARY_PATH=/opt/rocm/lib:$LD_LIBRARY_PATH
```

And can you confirm this link is valid?  
```
$ ll /opt/rocm/lib/libhip_hcc.so 
lrwxrwxrwx 1 root root 31 Jan 26 01:15 /opt/rocm/lib/libhip_hcc.so -> /opt/rocm/hip/lib/libhip_hcc.so
```

**Comment by mmmmming18** [comment]
@parallelo Hello,

> On a Vega machine with ROCm 1.7 installed, we were able to train ResNet on CIFAR-10 data.
We've got a couple known workarounds that may be useful for you. These will be included in an upcoming release. Anyway, we want you to be able to make progress in the meantime, so here they are:
sudo sh -c 'echo "options amdkfd noretry=0"        >> /etc/modprobe.d/amdkfd.conf'
sudo sh -c 'echo "options amdgpu vm_update_mode=0" >> /etc/modprobe.d/amdgpu.conf'
sudo update-initramfs -u
# then reboot

I followed your steps exactly and now I am getting "There is no device can be used to do the computation" error.

**Comment by mmmmming18** [comment]
/opt/rocm/bin/hipconfig
HIP version  : 1.4.17494

== hipconfig
HIP_PATH     : /opt/rocm/hip
HIP_PLATFORM : hcc
CPP_CONFIG   :  -D__HIP_PLATFORM_HCC__=   -I/opt/rocm/hip/include -I/opt/rocm/hcc/include

== hcc
HSA_PATH     : /opt/rocm/hsa
HCC_HOME     : /opt/rocm/hcc
HCC clang version 6.0.0 (ssh://gerritgit/compute/ec/hcc-tot/clang 42ceed861a212d9bd0aef883ee7981144f3ecc02) (ssh://gerritgit/compute/ec/hcc-tot/llvm 23e086be6f627e6e983c6789d2e77da6bf85ebb6) (based on HCC 1.1.17493-2f85d8a-42ceed8-23e086b )
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/hcc/bin
Can't exec "/opt/rocm/hcc/compiler/bin/llc": No such file or directory at /opt/rocm/bin/hipconfig line 132.
HCC-cxxflags :  -hc -std=c++amp -I/opt/rocm/hcc/includeHCC-ldflags  :  -hc -std=c++amp -L/opt/rocm/hcc/lib -Wl,--rpath=/opt/rocm/hcc/lib -ldl -lm -lpthread -lunwind -lhc_am -Wl,--whole-archive -lmcwamp -Wl,--no-whole-archive

=== Environment Variables
PATH=/home/mcong/bin:/home/mcong/.local/bin:/opt/rocm/hcc/bin:/opt/rocm/hip/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
LD_LIBRARY_PATH=/opt/rocm/lib
HIP_PATH=/opt/rocm/hip
HIP_VISIBLE_DEVICES=0
HCC_HOME=/opt/rocm/hcc

== Linux Kernel
Hostname     : databurner01
Linux databurner01 4.10.0-28-generic #32~16.04.2-Ubuntu SMP Thu Jul 20 10:19:48 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

**Comment by parallelo** [comment]
Please try another reboot and then see if you can build/run the following two HIP samples:
```
/opt/rocm/hip/samples/0_Intro/square/
/opt/rocm/hip/samples/1_Utils/hipInfo/
```
Also, can you check whether the ROCm-related kernel modules are loaded?  
```
lsmod | grep -E 'amdkfd|amdgpu'
```

**Comment by mmmmming18** [comment]
@parallelo 
lsmod | grep -E 'amdkfd|amdgpu'

amdkfd                221184  1
amd_iommu_v2           20480  1 amdkfd
amdgpu               3076096  2
amdttm                102400  1 amdgpu
amdkcl                 24576  3 amdttm,amdgpu,amdkfd
drm_kms_helper        151552  1 amdgpu
drm                   352256  6 amdttm,amdgpu,amdkcl,drm_kms_helper
i2c_algo_bit           16384  2 igb,amdgpu

**Comment by mmmmming18** [comment]
/opt/rocm/hip/samples/0_Intro/square$ export PATH=$PATH:/opt/rocm/hip/bin
/opt/rocm/hip/samples/0_Intro/square$ sudo hipify square.cu > square.cpp
-bash: square.cpp: Permission denied

What did I miss...

**Comment by parallelo** [comment]
Perhaps try copying the `hip/samples` directory under your `$HOME` directory.

**Comment by mmmmming18** [comment]
hipify: command not found

**Comment by parallelo** [comment]
Assuming you've got `hip` installed correctly:  `/opt/rocm/bin/hipify`

**Comment by mmmmming18** [comment]
It seems not... sorry
/opt/rocm/bin$ ls
amdhsacod     clang-ocl      finduncodep.sh  hccgenco.sh                hipconfig                  hipdemangleatp      hipify-cmakefile        rocm_agent_enumerator  rocm-smi
amdhsafin     extractkernel  hcc             hipcc                      hipconvertinplace-perl.sh  hipexamine-perl.sh  hipify-perl             rocminfo
clamp-config  findcode.sh    hcc-config      hipcc_cmake_linker_helper  hipconvertinplace.sh       hipexamine.sh       hsa-api-filter-cxl.txt  rocm-profiler

I followed the basic installation guide exactly this time, what did I miss?

**Comment by parallelo** [comment]
```

**Comment by parallelo** [comment]
```
$ make
/opt/rocm/hip/bin/hipify-perl square.cu > square.cpp
/opt/rocm/hip/bin/hipcc  square.cpp -o square.out
$ ./square.out 
info: running on device Device 6860
info: allocate host mem (  7.63 MB)
info: allocate device mem (  7.63 MB)
info: copy Host2Device
info: launch 'vector_square' kernel
info: copy Device2Host
info: check result
PASSED!
```

**Comment by mmmmming18** [comment]
make
/opt/rocm/hip/bin/hipcc  square.hipref.cpp -o square.hip.out

ls
Makefile  README.md  square.cpp  square.cu  square.hip.out  square.hipref.cpp

 ./square.hip.out 
There is no device can be used to do the computation

**Comment by parallelo** [comment]
How about the following?  
```         
$ cd /opt/rocm/hip/samples/1_Utils/hipInfo
$ sudo make
/opt/rocm/hip/bin/hipcc hipInfo.cpp -o hipInfo
$ ./hipInfo
...
```

**Comment by mmmmming18** [comment]
/opt/rocm/hip/samples/1_Utils/hipInfo$ sudo make
/opt/rocm/hip/bin/hipcc hipInfo.cpp -o hipInfo
cp hipInfo /opt/rocm/hip/bin

/opt/rocm/hip/samples/1_Utils/hipInfo$ ./hipInfo
compiler: hcc version=1.1.17493-2f85d8a-42ceed8-23e086b, workweek (YYWWD) = 17493
There is no device can be used to do the computation

**Comment by parallelo** [comment]
@jedwards-AMD - Any thoughts on next steps?  (`There is no device can be used to do the computation`)

ROCm kernel modules appear to be loaded fine on that system:  

> $ lsmod | grep -E 'amdkfd|amdgpu'
> amdkfd 221184 1
> amd_iommu_v2 20480 1 amdkfd
> amdgpu 3076096 2
> amdttm 102400 1 amdgpu
> amdkcl 24576 3 amdttm,amdgpu,amdkfd
> drm_kms_helper 151552 1 amdgpu
> drm 352256 6 amdttm,amdgpu,amdkcl,drm_kms_helper
> i2c_algo_bit 16384 2 igb,amdgpu

**Comment by jedwards-AMD** [comment]
Has this machine ever worked? Lets get the output of these commands:
.
dmesg | grep amdkfd
dmesg | grep amdgu
.
This will show me if the device is registered and if atomic support is available.

**Comment by mmmmming18** [comment]
@jedwards-AMD Hello, both commands give empty output.


This machine worked before. The first time I installed hiptensorflow the model was able to start training at least. This is my second time I installed hiptensorflow in a cleaned os and I just did some additional steps which are the commands that parallelo suggested:

> sudo sh -c 'echo "options amdkfd noretry=0"        >> /etc/modprobe.d/amdkfd.conf'
> sudo sh -c 'echo "options amdgpu vm_update_mode=0" >> /etc/modprobe.d/amdgpu.conf'
> sudo update-initramfs -u
> # then reboot

**Comment by jedwards-AMD** [comment]
Does rocminfo give any output? This command works at the base interface level, so it should show if you even have a device.

**Comment by mmmmming18** [comment]
`sudo usermod -a -G video $LOGNAME`

@jedwards-AMD This command solves everything. 

@parallelo Now I am able to train ResNet on CIFAR-10 data without any error. Thanks very much.

When can we expect new release? Does new release support newest version of tensorflow?

**Comment by parallelo** [comment]
Yes, that makes sense.  Happy to hear it is working now.
